name: Sync main branch to another repo

on:
  push:
    # Only run this workflow when the 'main' branch is pushed
    branches: [ main ] 
  
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source repository
        uses: actions/checkout@v4
        with:
          # We need to fetch all history for a force push to work correctly
          fetch-depth: 0

      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.REPO_SYNC_KEY }}

      - name: Push main branch and tags if author is authorized
        env:
          # Safely expose the secret as an environment variable
          AUTHORIZED_EMAIL: ${{ secrets.EMAIL }}
          DESTINATION_REPO: ${{ secrets.TARGET_REPO }}
        run: |
          # Use a shell 'if' to check the condition
          if [[ "${{ github.event_name }}" == "workflow_dispatch" || "${{ github.event.head_commit.author.email }}" == "${AUTHORIZED_EMAIL}" ]]; then
            echo "✅ Condition met. Pushing main branch and tags to destination."

            # 1. Force push the main branch. This overwrites the destination 'main'
            #    but does NOT touch any other branches.
            git push ${DESTINATION_REPO} main:main

            echo "Sync complete."
          else
            echo "❌ Author email does not match. Skipping sync."
          fi