# .github/workflows/sync-to-target.yml
name: Sync to another repo

on:
  push:
    branches: ["*"]
    tags: ["*"]
  workflow_dispatch:

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.REPO_SYNC_KEY }}

      # This is the corrected step
      - name: Mirror to destination if author is authorized
        # The env block safely exposes the secret to the run script
        env:
          AUTHORIZED_EMAIL: ${{ secrets.EMAIL }}
        run: |
          # This 'if' is a SHELL 'if', not a GitHub Actions 'if'.
          # It runs inside the job runner where secrets are available.
          
          # First, check if the workflow was manually triggered
          if [[ "${{ github.event_name }}" == "workflow_dispatch" ]]; then
            echo "Workflow was manually dispatched. Mirroring repository."
            git push --mirror ssh://git@github.com/weavertech-group/fmea-vis.git
            exit 0 # Exit successfully after push
          fi
          
          # If it was a push event, check the commit author's email
          echo "Event is a push. Checking commit author..."
          echo "Commit author email: ${{ github.event.head_commit.author.email }}"

          if [[ "${{ github.event.head_commit.author.email }}" == "${AUTHORIZED_EMAIL}" ]]; then
            echo "✅ Author email matches the authorized email. Mirroring repository."
            git push --mirror ssh://git@github.com/weavertech-group/fmea-vis.git
          else
            echo "❌ Author email does not match. Skipping mirror."
            # The step will still succeed, but the critical 'push' action is skipped.
          fi