name: Sync branch to another repo

on:
  push:
    branches:
      - '**'
  
  workflow_dispatch:

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source repository
        uses: actions/checkout@v4
        with:
          # We need to fetch all history for a force push to work correctly
          fetch-depth: 0

      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.REPO_SYNC_KEY }}

      - name: Push branch to destination if author is authorized
        env:
          # Safely expose secrets as environment variables
          AUTHORIZED_EMAIL: ${{ secrets.EMAIL }}
          DESTINATION_REPO: ${{ secrets.TARGET_REPO }}
        run: |
          if [[ "${{ github.event_name }}" == "workflow_dispatch" || "${{ github.event.head_commit.author.email }}" == "${AUTHORIZED_EMAIL}" ]]; then
            BRANCH_NAME="${{ github.ref_name }}"

            echo "✅ Authorization check passed. Pushing branch '${BRANCH_NAME}' to destination."
            git push "${DESTINATION_REPO}" "${BRANCH_NAME}:${BRANCH_NAME}"

            echo "Sync complete."
          else
            echo "❌ Push author email ('${{ github.event.head_commit.author.email }}') does not match the authorized email. Skipping sync."
          fi
